apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |-
    your.domain:53 {
        errors
        template IN A your.domain {
            answer "{{ .Name }} 60 IN A 10.100.197.118"
        }
    }
    nestix.dev:53 {
        errors
        template IN A nestix.dev {
            answer "{{ .Name }} 60 IN A 10.100.197.118"
        }
    }
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
