apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  # Remove the annotation below if you don't want traefik to be the default ingress class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: traefik.io/ingress-controller
